### ISSUE TITLE
obsolete confusing sql schema's

### ISSUE THREAD

**Issue by cookie33** [CatchPlus/EPIC-API-v2#49]
Hi,

The sql schema: epic.sql and schema.sql are old an dobsolete. Can they be removed from the code? They are very confusing.

Can a working copy of the needed sql schema be included?

Greetings,

Robert Verkerk

**Comment by TobiasWeigel** [comment]
I think this has been addressed in commit 049be47b89c63db3842e161b48d1b961b29caf25.
Closing.
