### ISSUE TITLE
config.rb.example has default gwdgpid profile set. This is wrong for many new installations.

### ISSUE THREAD

**Issue by cookie33** [CatchPlus/EPIC-API-v2#51]
Hi,

The file config.rb.example has as a default profile gwdgpid set. The file config.rb.example should state that this is optional and show the possibility's. It should also point out the differences between:
- no profile set       # default
- gwdgpid profile   # This profile disables the deletion of all pids that match some regular expression. 
- no delete profile  # This profile provides support for sharing a prefix between multiple institutes

There are differences how PID's are generated/assigned between the default profile and the gwdgpid profile. This should also be mentioned.

Greetings,

Robert Verkerk

**Comment by TobiasWeigel** [comment]
Hi Robert,
first of all, thanks for taking care of this. I've reviewed your changes for the authentication config and readme and will merge this immediately.
Regarding the profiles in config.rb, I agree with what you write here, and think it would be best if this was stated directly in a comment at the ENFORCED_PROFILES setting in config.rb. Can we perhaps find a more fitting name for the gwgpid profile? That would help, too; maybe 'nodelete-regex' or 'nodelete-ifmatch'.
If you commit, I'll also quickly merge this.

Best, Tobias

**Comment by cookie33** [comment]
Hi,

I did something wrong here. The descriptions where switched around for no_delete and gwdgpid. It should have been:

* no profile set      # default
* gwdgpid profile  # This profile provides support for sharing a prefix between multiple institutes.
* no delete profile # This profile disables the deletion of all pids that match some regular expression.

Greetings,

Robert

**Comment by cookie33** [comment]
Hi,

I created a pull request which would take care of it..

It is number #52 I think.

Robert Verkerk

**Comment by TobiasWeigel** [comment]
Done in 5d0c987aff5d0eaedb42b44b334f14adac06b6fa.
Closed.
